# Generated by Django 5.2.6 on 2025-09-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='matric_no',
            new_name='roll_no',
        ),
    ]
