# Generated by Django 5.2.6 on 2025-09-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='model_mame',
            new_name='model_name',
        ),
    ]
